# description: |
#     Assumptions: Git Merge is used so context and history are available
#     Simple and familiar.
#     Preserves complete history and chronological order.
#     Maintains the context of the branch.
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:  
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: get pull request of current sha // (we assume there is one)
        id: prdetail
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = new Octokit()
            await octokit.request('GET /repos/{owner}/{repo}/commits/{commit_sha}/pulls', {
              owner: 'OWNER',
              repo: 'REPO',
              commit_sha: 'COMMIT_SHA'
            })
      - name: Get result
        run: echo "${{steps.prdetail.outputs.result}}"
